version: 0.1.{build}
image: Visual Studio 2017

branches:
  except:
    - gh-pages

install:
  - ps: |
      $osVersion = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").BuildLabEx
      $psVersion = $PSVersionTable.PSVersion
      Write-Host "Server version ${osVersion}"
      Write-Host "PowerShell version ${psVersion}"
      docker version
  - ps: |
      Install-PackageProvider -Name "NuGet" -Force
      Install-Module "Pester", "PSScriptAnalyzer" -SkipPublisherCheck -Force

build_script:
  - ps: .\Build.ps1

test_script:
  - ps: .\Test.ps1
