version: 0.1.{build}
image: Visual Studio 2017

branches:
  except:
    - gh-pages

environment:
  PSRepositoryName:
    secure: rNmqtztDt57vkUO+OAPCmg==
  PSRepositoryLocation:
    secure: VMUmmeqFeGKU3cgQY6BWJxttrgYE+ulY/N/UrzT54Iz/91LROC/nd4bGCF5cRwmA
  PSRepositoryApiKey:
    secure: cT+Kpb3jguYeMikGDpbfLKe1FKzY+/MUYRE7TS0c5f4=

install:
  - ps: .\Install.ps1
  - ps: |
      Register-PSRepository $env:PSRepositoryName -SourceLocation $env:PSRepositoryLocation -PublishLocation $env:PSRepositoryLocation -InstallationPolicy Trusted
      Get-PSRepository

build_script:
  - ps: .\Build.ps1 -Version $env:APPVEYOR_BUILD_VERSION

test_script:
  - ps: .\Test.ps1

deploy_script:
  - ps: .\Deploy.ps1 -ApiKey $env:PSRepositoryApiKey -Repository $env:PSRepositoryName
