version: 0.1.{build}
image: Visual Studio 2017

branches:
  except:
    - gh-pages

environment:
  RepositoryName: BCHGallery
  RepositoryUrl:
    secure: VMUmmeqFeGKU3cgQY6BWJxttrgYE+ulY/N/UrzT54Iz/91LROC/nd4bGCF5cRwmA
  RepositoryApiKey:
    secure: cT+Kpb3jguYeMikGDpbfLKe1FKzY+/MUYRE7TS0c5f4=

install:
  - ps: .\Install.ps1
  - ps: |
      Register-PSRepository $env:RepositoryName -SourceLocation $env:RepositoryUrl -PublishLocation $env:RepositoryUrl
      Get-PSRepository

build_script:
  - ps: .\Build.ps1 -Version $env:APPVEYOR_BUILD_VERSION

test_script:
  - ps: .\Test.ps1

deploy_script:
  - ps: .\Deploy.ps1 -ApiKey $env:RepositoryApiKey -Repository $env:RepositoryName
