version: 0.1.{build}
image: Visual Studio 2017

branches:
  except:
    - gh-pages

environment:
  RepositoryName: BCHGallery
  RepositoryUrl:
    secure: K0PjtWmPZFi+OUNMJCy7E3flpk6Vy/Wm/9UBRDmocEl0auYvAjd/HVjKIb/UkYmQBNQupFWXNaFST3Nhez2kaA==
  RepositoryApiKey:
    secure: cT+Kpb3jguYeMikGDpbfLKe1FKzY+/MUYRE7TS0c5f4=

install:
  - ps: .\Install.ps1
  - ps: Register-PSRepository $env:RepositoryName -SourceLocation $env:RepositoryUrl -PublishLocation $env:RepositoryUrl

build_script:
  - ps: .\Build.ps1 -BuildVersion $env:APPVEYOR_BUILD_VERSION

test_script:
  - ps: .\Test.ps1

deploy_script:
  - ps: .\Deploy.ps1 -ApiKey $env:RepositoryApiKey -Repository $env:RepositoryName
